# Copyright 2016 Edward Diener
# Copyright 2017 Cromwell D. Enage
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://boost.org/LICENSE_1_0.txt)

language: cpp

python: "2.7"

branches:
  only:
    - master
    - develop
    - /feature\/.*/

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      compiler: clang++-6.0
      env: TOOLSET=clang COMPILER=clang++-6.0 CXXSTD=03,11,14,1z,2a
      addons:
        apt:
          packages:
            - clang-6.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0

    - os: linux
      compiler: clang++-7
      env: TOOLSET=clang COMPILER=clang++-7 CXXSTD=14,1z,2a
      addons:
        apt:
          packages:
            - clang-7
            - libc6-dbg
            - libc++-dev
            - libstdc++-8-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7

    - os: linux
      compiler: clang++-8
      env: TOOLSET=clang COMPILER=clang++-8 CXXSTD=14,1z,2a
      addons:
        apt:
          packages:
            - clang-8
            - libc6-dbg
            - libc++-dev
            - libstdc++-8-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8

    - os: linux
      compiler: clang++
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      compiler: clang++-libc++
      env: TOOLSET=clang COMPILER=clang++-libc++ CXXSTD=03,11,14,1z
      addons:
        apt:
          packages:
            - libc++-dev

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=03,11,14,1z
      osx_image: xcode7.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=03,11,14,1z
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=03,11,14,1z
      osx_image: xcode9.4.1

install:
  - BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - git submodule update --init libs/parameter_python
  - git submodule update --init tools/boost_install
  - git submodule update --init libs/headers
  - cp -r $TRAVIS_BUILD_DIR/* libs/parameter
  - python tools/boostdep/depinst/depinst.py parameter
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER ;" > ~/user-config.jam
  - ./b2 --verbose-test libs/config/test//config_info toolset=$TOOLSET cxxstd=$CXXSTD || true
  - cd libs/parameter/test
  - ../../../b2 -j`(nproc || sysctl -n hw.ncpu) 2> /dev/null` toolset=$TOOLSET cxxstd=$CXXSTD $CXXSTD_DIALECT
  - cd ../../..

notifications:
  email:
    on_success: always
